Implement github workflow events (Dispatch, Job, Run)
go-playground/webhooks pull request #139
Opened 2021-10-25 20:15 UTC by dvonthenen

This PR implements event processing for GitHub `workflow_dispatch`:
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_dispatch

`workflow_job`:
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_job

and `workflow_run`:
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run

This implementation has been verified in a production environment (https://github.com/vmware-tanzu/community-edition) and details on its use can be found in this PR: https://github.com/vmware-tanzu/community-edition/pull/2300

2021-11-14 04:49 UTC, tohjustin requested changes
Thanks for creating this PR! Would also like to see support for GitHub workflow events in this package.

2021-11-14 04:49 UTC, tohjustin commented on github/github.go
> +	WorklowDispatchEvent                     Event = "workflow_dispatch"
```suggestion
	WorkflowDispatchEvent                    Event = "workflow_dispatch"
```

2021-11-15 16:56 UTC, dvonthenen commented on github/github.go
> +	WorklowDispatchEvent                     Event = "workflow_dispatch"
Good catch!

2021-11-15 17:17 UTC, dvonthenen commented
> Thanks for creating this PR! Would also like to see support for GitHub workflow events in this package.

Not sure what you mean... could you point me out to where these events are in the code base?

2021-11-16 01:47 UTC, tohjustin commented
> > Thanks for creating this PR! Would also like to see support for GitHub workflow events in this package.
> 
> Not sure what you mean... could you point me out to where these events are in the code base? I'm fairly new to the GitHub webhook stuff.

Sorry, I meant to say that I would like to see your changes in this PR merged. (I believe you have already implemented all the [workflow-based webhook events that GitHub supports](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_dispatch)) 😄

@deankarn @Toshik1978 By any chance either of you are free this week to review this? Thank you 🙏🏼

2021-11-16 02:14 UTC, dvonthenen commented
Ahhhhh ok... I thought it was something I was missing or something.

2021-11-16 16:56 UTC, merged

2021-11-17 08:51 UTC, tohjustin commented
Thanks @dvonthenen & @Toshik1978!