feat: implement gitlab release webhook
go-playground/webhooks pull request #174
Opened 2023-06-13 11:05 UTC by xNok

https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html#release-events

2023-07-17 19:44 UTC, robinlieb requested changes
Generally looks good, could you please revert the mentioned changes?

2023-07-17 19:44 UTC, robinlieb commented on gitlab/gitlab_test.go
> -		t.Run(tt.name, func(t *testing.T) {
Could you please revert this change and the indentation of the following lines?

2023-07-17 19:44 UTC, robinlieb commented on gitlab/gitlab_test.go
> -		t.Run(tt.name, func(t *testing.T) {
Could you please revert this change and the indentation of the following lines?

2023-07-17 19:44 UTC, robinlieb commented on gitlab/gitlab_test.go
> -		t.Run(tt.name, func(t *testing.T) {
Could you please revert this change and the indentation of the following lines?

2023-07-17 19:44 UTC, robinlieb commented on gitlab/gitlab_test.go
> -		t.Run(tt.name, func(t *testing.T) {
Could you please revert this change and the indentation of the following lines?

2023-10-10 10:47 UTC, xNok commented
Sorry kinda forgot about this one, I reverted the indentation changes in the test

2023-11-07 17:52 UTC, robinlieb approved these changes

2023-11-07 17:53 UTC, merged

2023-11-07 17:53 UTC, robinlieb commented
@xNok Thanks!